language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "tangbogreat"
  - git config user.email "martintang@tencent.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" deploy:deploy
# E: Build LifeCycle

branches:
  only:
    - deploy
env:
 global:
   - GH_REF: github.com/tangbogreat/blogs.git